spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: preco-fipe
  datasource:
    url: jdbc:mysql://localhost:3306/preco_fipe?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_MYSQL_ROOT_USER}
    password: ${ENV_MYSQL_ROOT_PASSWORD}
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
      threads:
        max: 20

fipe-api:
  base-url: https://fipe.parallelum.com.br/api
  brands-uri: /v2/{vehicleType}/brands
  models-uri: /v2/{vehicleType}/brands/{brandId}/models
  years-uri: /v2/{vehicleType}/brands/{brandId}/models/{modelId}/years
  fipe-information-uri: /v2/{vehicleType}/brands/{brandId}/models/{modelId}/years/{yearId}

